"""empty message

Revision ID: 09b2f2ec0ec3
Revises: 540f67428c34
Create Date: 2026-04-01 08:46:36.803836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b2f2ec0ec3'
down_revision = '540f67428c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
